apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
      - name: nodeserver
        image: bharatverman/learndevops
        ports:
        - containerPort: 8081
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: webapp 
  type: nodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31110
